# Generated by Django 3.0.5 on 2021-05-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=12)),
                ('fromlocation', models.CharField(max_length=256)),
                ('tolocation', models.CharField(max_length=256)),
                ('trucktype', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=12)),
                ('fromlocation', models.CharField(max_length=256)),
                ('tolocation', models.CharField(max_length=256)),
                ('trucktype', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField()),
                ('nooftrucks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=12)),
                ('trucktype', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('tonnage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BookVehicle')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RegisterVehicle')),
            ],
        ),
    ]
